#配置文件可以配置那些东西
#官方配置太多了解原理
#name: wengkehao #字符串可以不打引号,也可打单引号或双引号
debug: true

age: ~
#对象
student:
  name: a
  age: b
#行内写法
student2: {name: c,age: 5}

#数组
pets:
  - cat
  - dog
#数组行内写法
pets2: [cat,dog]

server:
  port: 8080
  servlet:
    context-path: /


spring:
  mvc:
    format:
      date: dd/MM/yyyy #自定义配置日期转换器
  thymeleaf:
    cache: false #关闭模板缓存
  messages:
    basename: i18n.login  #配置文件位置, 识别国际化


dog:
  name: ${dog.hello:hello}_wangcai
  age: 4

user:
  name: wengkehao2${random.uuid}
  age: 12
  flag: true
  date: 2020/12/12
  map: {k1: v1,k2: v2}
  list:
    - dog
  dog: dog

