server:
  port: 9006

spring:
  application:
    name: cloud-gateway-9006
  cloud:
    discovery:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心网关功能
      routes:
          - id: albaba-nacos-consumer-nacos #路由id,名称没有要求,但是保证唯一,建议匹配服务名
            uri: http://localhost:9003/albaba-nacos-consumer-nacos
            predicate: #断言
              - Path: /consumer/** #断言：路径相匹配进行路由

          - id: 22 #路由id,名称没有要求,但是保证唯一,建议匹配服务名  配置多个
              uri: http://localhost:9003  #lb://albaba-nacos-consumer-nacos gateway负债均衡用lb
              predicate: #断言
                - Path: /consumer/** #断言：路径相匹配进行路由

debug: true
