##springboot内置oracle jdbc参数
#spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@172.117.145.113:1521:oratest
#spring.datasource.username=root
#spring.datasource.password=best
##数据源类型:c3p0
#spring.datasource.type=com.mchange.v2.c3p0.ComboPooledDataSource
#————————————————
#版权声明：本文为CSDN博主「mlsama」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
#原文链接：https://blog.csdn.net/mlsama/article/details/81202612


spring:
  datasource:
    username: wengkeh
    password: wengkeh
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
  profiles:
    active: test

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.tfb.pojo

